import { Post, Route, Controller, Request, Get } from "tsoa";
import { AppDataSource } from "../../data-source";
import { Uploads } from "../../entities/Uploads";
import * as path from "path";
import multer from "multer";
import { Request as ExpressRequest } from "express";
import { decodeToken, getTokenFromRequest } from "../utilities/TokenUtility";

import { randomBytes } from "crypto";


const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, "uploads/public");
  },
  filename: (req, file, cb) => {
    const extname = path.extname(file.originalname);
    const uniqueFileName = randomBytes(16).toString("hex") + extname;
    cb(null, uniqueFileName);
  },
});

const upload = multer({ storage }).any();

@Route("filemanager")
export class FileManagerController extends Controller {
  @Get("/photos")
  public async getFiles(@Request() request: any): Promise<{
    message: string;
    data?: any[];
    statusCode: number;
  }> {
    try {
      const uploadsRepository = AppDataSource.getRepository(Uploads);
      const token = getTokenFromRequest(request);
      const decodedToken = decodeToken(token);

      if (!decodedToken || typeof decodedToken !== "object") {
        return { message: "Invalid token", data: [], statusCode: 401 };
      }

      const userId = decodedToken.userId;
      const uploads = await uploadsRepository.find({
        where: { user_id: userId },
        order: { id: "desc" },
      });

      if (!uploads.length) {
        return { message: "No photos found", data: [], statusCode: 404 };
      }

      const data = uploads.map((upload) => ({
        id: upload.id,
        fileOriginalName: upload.file_original_name,
        fileName: upload.file_name,
        userId: upload.user_id,
      }));

      return { message: "Files retrieved successfully", data, statusCode: 200 };
    } catch (error) {
      console.error("Error retrieving files:", error);
      return { message: "Failed to retrieve files", data: [], statusCode: 500 };
    }
  }
  
  @Post("/upload")
  public async uploadImage(@Request() request: ExpressRequest): Promise<{ message: string; data?: any; statusCode: number }> {
    return new Promise((resolve, reject) => {
      upload(request, request.res!, async (err: any) => {
        if (err) {
          console.error("Multer error:", err);
          return reject({ message: "Error uploading files", statusCode: 500 });
        }

        const files = request.files as Express.Multer.File[];

        if (!files || files.length === 0) {
          return resolve({ message: "No files uploaded", statusCode: 422 });
        }

        const uploadsRepository = AppDataSource.getRepository(Uploads);
        const token = getTokenFromRequest(request);
        const decodedToken = decodeToken(token);

        if (!decodedToken || typeof decodedToken !== "object") {
          return resolve({ message: "Invalid token", statusCode: 401 });
        }

        const userId = decodedToken.userId;
        const savedFiles = [];

        try {
          for (const file of files) {
            // Use the filename generated by Multer
            const newImage = uploadsRepository.create({
              file_original_name: file.originalname,
              file_name: `public/${file.filename}`, // <-- This ensures the filename matches what Multer saved
              user_id: userId,
            });

            const savedImage = await uploadsRepository.save(newImage);
            savedFiles.push({
              id: savedImage.id,
              fileOriginalName: savedImage.file_original_name,
              fileName: savedImage.file_name,
              userId: savedImage.user_id,
            });
          }

          return resolve({
            message: "Files uploaded successfully",
            data: savedFiles,
            statusCode: 200,
          });
        } catch (error) {
          console.error("Error saving files:", error);
          return resolve({ message: "Failed to upload files", statusCode: 500 });
        }
      });
    });
  }
}
