export const breedsByType = {
  Dog: [
    "Affenpinscher",
    "Afghan Hound",
    "Airedale Terrier",
    "Akita",
    "Alaskan Malamute",
    "American Bulldog",
    "American Cocker Spaniel",
    "American Eskimo Dog",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "Anatolian Shepherd Dog",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Australian Terrier",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Belgian Malinois",
    "Belgian Sheepdog",
    "Belgian Tervuren",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Black and Tan Coonhound",
    "Bloodhound",
    "Border Collie",
    "Border Terrier",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Briard",
    "Brittany",
    "Brussels Griffon",
    "Bull Terrier",
    "Bulldog",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corso",
    "Cardigan Welsh Corgi",
    "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chinese Crested",
    "Chow Chow",
    "Clumber Spaniel",
    "Cocker Spaniel",
    "Collie",
    "Dachshund",
    "Dalmatian",
    "Doberman Pinscher",
    "Dogo Argentino",
    "English Cocker Spaniel",
    "English Setter",
    "English Springer Spaniel",
    "French Bulldog",
    "German Pinscher",
    "German Shepherd",
    "German Shorthaired Pointer",
    "Giant Schnauzer",
    "Golden Retriever",
    "Gordon Setter",
    "Great Dane",
    "Great Pyrenees",
    "Greyhound",
    "Havanese",
    "Irish Setter",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Japanese Chin",
    "Keeshond",
    "Komondor",
    "Kuvasz",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Leonberger",
    "Lhasa Apso",
    "Maltese",
    "Mastiff",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Neapolitan Mastiff",
    "Newfoundland",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Old English Sheepdog",
    "Papillon",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Pharaoh Hound",
    "Plott Hound",
    "Pointer",
    "Pomeranian",
    "Poodle",
    "Portuguese Water Dog",
    "Pug",
    "Rottweiler",
    "Saint Bernard",
    "Samoyed",
    "Schipperke",
    "Scottish Terrier",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Soft Coated Wheaten Terrier",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Vizsla",
    "Weimaraner",
    "West Highland White Terrier",
    "Whippet",
    "Yorkshire Terrier",
    "Goldendoodle",
    "Labradoodle",
    "Cockapoo",
    "Bernedoodle",
    "Cavapoo",
    "Maltipoo",
    "Pomsky",
    "Puggle",
    "Morkie",
    "Aussiedoodle",
    "Sheepadoodle",
    "Chiweenie",
    "Cavachon",
    "Yorkipoo",
    "Mal-Shi",
    "Whoodle",
    "Schnoodle",
    "Peekapoo",
    "Horgi",
    "Boxador",
    "Shih-Poo",
    "Chug",
    "Pomchi",
    "Goldador",
    "Frenchie Pug",
    "Gerberian Shepsky",
    "Bullmation",
    "Pitsky",
    "Saint Berdoodle",
    "Doxiepoo",
    "Cheagle",
    "Shorkie",
    "Westiepoo",
    "Bordoodle",
    "Pyredoodle",
    "Newfypoo",
    "Jackabee",
    "Corgipoo",
    "Beaglier",
    "Bassador",
  ],
  Cat: [
    "Abyssinian",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Balinese",
    "Bengal",
    "Birman",
    "Bombay",
    "British Longhair",
    "British Shorthair",
    "Burmese",
    "Burmilla",
    "Chartreux",
    "Cornish Rex",
    "Devon Rex",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Havana Brown",
    "Himalayan",
    "Japanese Bobtail",
    "Korat",
    "LaPerm",
    "Maine Coon",
    "Manx",
    "Munchkin",
    "Norwegian Forest Cat",
    "Ocicat",
    "Oriental Shorthair",
    "Persian",
    "Ragdoll",
    "Russian Blue",
    "Savannah",
    "Scottish Fold",
    "Selkirk Rex",
    "Siamese",
    "Siberian",
    "Singapura",
    "Snowshoe",
    "Somali",
    "Sphynx",
    "Tonkinese",
    "Turkish Angora",
    "Turkish Van",
    "Domestic Short Hair",
    "Domestic Long Hair",
    "Mixed Breed",
  ],
  Rabbit: [
    "Dutch",
    "Lionhead",
    "Flemish Giant",
    "Mini Lop",
    "English Lop",
    "Rex",
    "Hotot",
    "Angora",
    "Silver Marten",
    "Himalayan",
  ],
  Exotic: [
    "Sugar Glider",
    "Hedgehog",
    "Ferret",
    "Chinchilla",
    "Parrot",
    "Tarantula",
    "Bearded Dragon",
    "Gecko",
    "Iguana",
    "Skink",
  ],
};

export const colorOptions = [
  { value: "Black", label: "Black" },
  { value: "White", label: "White" },
  { value: "Brown", label: "Brown" },
  { value: "Tan", label: "Tan" },
  { value: "Golden", label: "Golden" },
  { value: "Cream", label: "Cream" },
  { value: "Grey", label: "Grey" },
  { value: "Silver", label: "Silver" },
  { value: "Red", label: "Red" },
  { value: "Blue", label: "Blue" },

  { value: "Black & White", label: "Black & White" },
  { value: "Brown & White", label: "Brown & White" },
  { value: "Tan & White", label: "Tan & White" },
  { value: "Golden & White", label: "Golden & White" },

  { value: "Brindle", label: "Brindle" },
  { value: "Merle", label: "Merle" },
  { value: "Spotted", label: "Spotted" },
  { value: "Tabby", label: "Tabby" },
  { value: "Calico", label: "Calico" },
  { value: "Tortoiseshell", label: "Tortoiseshell" },

  { value: "Tri-color", label: "Tri-color" },
  { value: "Mixed", label: "Mixed / Other" },
];
